"""Drosophila Retina & Visual Preprocessing Module (Hassenstein-Reichardt Motion Correlator).

This module implements Module 2 of the Drosophila Vision-Motor Loop:
1. Spatial downscaling to a binocular ommatidia grid (16x32: 2 eyes of 16x16).
2. Photoreceptor adaptation (LMC Lamina contrast filtering).
3. ON / OFF pathway decomposition (T4/T5 inputs).
4. Elementary Motion Detectors (Hassenstein-Reichardt Correlators, 2D EMD).
5. Projection to Lobula Plate Tangential Cells (LPTC: HS-Left, HS-Right, VS-Forward).
6. Generation of stimulation currents I_ext and Poisson spike encoding for the SNN.
7. Rich real-time visual dashboard showing the fly's eye view.
"""

from __future__ import annotations

import argparse
import logging
import time
from collections import deque
from dataclasses import dataclass
from typing import Deque, Dict, Optional, Tuple

import cv2
import numpy as np

import config

logger = logging.getLogger("Retina")


@dataclass
class RetinaOutput:
    """Encapsulates all visual feature representations generated by the fly retina."""

    # Ommatidia arrays
    ommatidia_luminance: np.ndarray      # Shape: (16, 32) float [0, 1]
    delta_luminance: np.ndarray          # Shape: (16, 32) float [-1, 1]
    on_channel: np.ndarray               # Shape: (16, 32) float >= 0 (T4 input)
    off_channel: np.ndarray              # Shape: (16, 32) float >= 0 (T5 input)

    # 2D Hassenstein-Reichardt Correlator (EMD) fields
    emd_x: np.ndarray                    # Shape: (16, 31) float: +right, -left
    emd_y: np.ndarray                    # Shape: (15, 32) float: +down, -up

    # Lobula Plate Tangential Cell (LPTC) integrated signals
    lptc_hs_left: float                  # Left eye horizontal flow (yaw rightward)
    lptc_hs_right: float                 # Right eye horizontal flow (yaw leftward)
    lptc_vs_forward: float               # Forward optic flow expansion (speed cue)
    lptc_yaw_signal: float               # Net yaw rotation (HS_left - HS_right)

    # Synaptic stimulation currents for the SNN
    stimulation_currents: np.ndarray     # 1D array of I_ext (features concatenated)
    spikes: np.ndarray                   # Binary spike vector [0, 1] (Poisson rate encoded)

    # Diagnostics
    processing_time_ms: float            # Execution time in ms


class DrosophilaRetina:
    """Simulates the bio-physical visual preprocessing cascade of Drosophila melanogaster."""

    def __init__(
        self,
        grid_height: int = config.RETINA_GRID_HEIGHT,
        grid_width: int = config.RETINA_GRID_WIDTH,
        lowpass_alpha: float = config.HRC_LOWPASS_ALPHA,
        optic_flow_gain: float = config.OPTIC_FLOW_GAIN,
        separate_on_off: bool = config.ON_OFF_SEPARATION,
    ) -> None:
        self.height = grid_height
        self.width = grid_width
        self.half_w = grid_width // 2
        self.alpha = float(lowpass_alpha)
        self.gain = float(optic_flow_gain)
        self.separate_on_off = separate_on_off

        # Temporal buffers for motion detection
        self.prev_luminance: Optional[np.ndarray] = None
        self.delayed_luminance: Optional[np.ndarray] = None

        # Precompute radial optical flow expansion template (Focus of Expansion, FOE)
        # Assuming car driving straight, FOE is at center horizon (y=0.45*H, x=0.5*W)
        cy, cx = self.height * 0.45, self.width * 0.50
        y_coords, x_coords = np.mgrid[0 : self.height, 0 : self.width]
        dy = y_coords - cy
        dx = x_coords - cx
        r = np.sqrt(dx**2 + dy**2) + 1e-5
        # Unit vector pointing outward from FOE
        self.foe_dir_x = (dx / r).astype(np.float32)
        self.foe_dir_y = (dy / r).astype(np.float32)

    def reset(self) -> None:
        """Reset temporal filters and state."""
        self.prev_luminance = None
        self.delayed_luminance = None

    def process(self, frame_bgr: np.ndarray, dt_s: float = 1.0 / 60.0) -> RetinaOutput:
        """Process a raw video frame into biological signals and stimulation currents."""
        t0 = time.perf_counter_ns()

        # Step 1: Photoreceptor transduction & Lamina LMC adaptation
        lum = self._transduce_photoreceptors(frame_bgr)

        # Initialize temporal state on first frame
        if self.prev_luminance is None:
            self.prev_luminance = lum.copy()
            self.delayed_luminance = lum.copy()

        # Step 2: Temporal difference (delta I) and ON/OFF pathways
        delta_i = lum - self.prev_luminance
        on_ch = np.maximum(delta_i, 0.0)
        off_ch = np.maximum(-delta_i, 0.0)

        # Step 3: Hassenstein-Reichardt Correlators (2D EMD)
        # Delayed arm lowpass filtering: I_delayed[t] = alpha * I_delayed[t-1] + (1 - alpha) * I[t]
        self.delayed_luminance = (
            self.alpha * self.delayed_luminance + (1.0 - self.alpha) * lum
        )

        emd_x, emd_y = self._compute_hrc(lum, self.delayed_luminance)

        # Step 4: Lobula Plate Tangential Cells (LPTC) integration
        hs_left, hs_right, vs_forward, yaw = self._extract_lptc(emd_x, emd_y)

        # Step 5: Synthesize synaptic stimulation currents I_ext
        currents = self._generate_currents(lum, delta_i, emd_x, emd_y, hs_left, hs_right, vs_forward)

        # Step 6: Poisson rate spike generation
        spikes = self._rate_encode_spikes(currents, dt_s)

        # Update previous frame
        self.prev_luminance = lum.copy()

        proc_ms = (time.perf_counter_ns() - t0) / 1_000_000.0

        return RetinaOutput(
            ommatidia_luminance=lum,
            delta_luminance=delta_i,
            on_channel=on_ch,
            off_channel=off_ch,
            emd_x=emd_x,
            emd_y=emd_y,
            lptc_hs_left=hs_left,
            lptc_hs_right=hs_right,
            lptc_vs_forward=vs_forward,
            lptc_yaw_signal=yaw,
            stimulation_currents=currents,
            spikes=spikes,
            processing_time_ms=proc_ms,
        )

    def _transduce_photoreceptors(self, frame_bgr: np.ndarray) -> np.ndarray:
        """Simulate ommatidial optics (Gaussian acceptance angle blur) and Lamina contrast adaptation."""
        # 1. Optical Gaussian blur simulating ommatidia acceptance angle (~5 deg)
        blurred = cv2.GaussianBlur(frame_bgr, (7, 7), 2.0)

        # 2. Downsample to (width, height) = (32, 16)
        ommatidia = cv2.resize(
            blurred,
            (self.width, self.height),
            interpolation=cv2.INTER_AREA,
        )

        # 3. Drosophila R1-R6 photoreceptors spectral weighting (Green: 58%, Blue/UV: 30%, Red: 12%)
        # Note: frame_bgr has channels [B, G, R]
        b = ommatidia[:, :, 0].astype(np.float32) / 255.0
        g = ommatidia[:, :, 1].astype(np.float32) / 255.0
        r = ommatidia[:, :, 2].astype(np.float32) / 255.0
        lum = 0.58 * g + 0.30 * b + 0.12 * r

        # 4. Photoreceptor non-linear saturation (Naka-Rushton response curve: V = I / (I + I_50))
        # Biophysically models rhodopsin transduction and prevents zero-contrast collapse
        adapted = lum / (lum + 0.35)
        return adapted.astype(np.float32)

    def _compute_hrc(
        self,
        current: np.ndarray,
        delayed: np.ndarray,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Compute horizontal and vertical 2D Elementary Motion Detectors (EMD).

        Full balanced correlator:
        EMD_x = Delayed(x) * Current(x+1) - Current(x) * Delayed(x+1)
        EMD_y = Delayed(y) * Current(y+1) - Current(y) * Delayed(y+1)
        """
        # Horizontal motion correlator across columns (shape: 16 x 31)
        # Left-to-right (rightward motion: +)
        c_right = delayed[:, :-1] * current[:, 1:]
        # Right-to-left (leftward motion: -)
        c_left = current[:, :-1] * delayed[:, 1:]
        emd_x = (c_right - c_left) * self.gain

        # Vertical motion correlator across rows (shape: 15 x 32)
        # Top-to-bottom (downward motion: +)
        c_down = delayed[:-1, :] * current[1:, :]
        # Bottom-to-top (upward motion: -)
        c_up = current[:-1, :] * delayed[1:, :]
        emd_y = (c_down - c_up) * self.gain

        return emd_x.astype(np.float32), emd_y.astype(np.float32)

    def _extract_lptc(
        self,
        emd_x: np.ndarray,
        emd_y: np.ndarray,
    ) -> Tuple[float, float, float, float]:
        """Extract Lobula Plate Tangential Cell (LPTC) responses.

        - Left Eye HS: horizontal flow in left hemifield
        - Right Eye HS: horizontal flow in right hemifield
        - Forward VS: expansion flow diverging outwards and downwards from horizon
        - Yaw: differential horizontal flow (HS_L - HS_R)
        """
        # Left eye hemifield (columns 0..15), Right eye hemifield (columns 16..31)
        # Note: emd_x has 31 columns: split at column 15
        hs_left_raw = float(np.mean(emd_x[:, :15]))
        hs_right_raw = float(np.mean(emd_x[:, 15:]))

        # Pad EMDs to match grid size (16, 32) for vector dot product
        flow_x = np.pad(emd_x, ((0, 0), (0, 1)), mode="edge")
        flow_y = np.pad(emd_y, ((0, 1), (0, 0)), mode="edge")

        # Forward translational expansion: dot product with FOE outward unit vectors
        expansion_map = flow_x * self.foe_dir_x + flow_y * self.foe_dir_y
        vs_forward = float(np.mean(expansion_map))

        # Yaw rotation signal: progressive vs regressive motion difference
        yaw = hs_left_raw - hs_right_raw

        return hs_left_raw, hs_right_raw, vs_forward, yaw

    def _generate_currents(
        self,
        lum: np.ndarray,
        delta_i: np.ndarray,
        emd_x: np.ndarray,
        emd_y: np.ndarray,
        hs_l: float,
        hs_r: float,
        vs_f: float,
    ) -> np.ndarray:
        """Flatten and scale visual signals into a 1D synaptic current vector I_ext."""
        # 1. Ommatidia static luminance (512 values)
        lum_flat = lum.ravel()

        # 2. Transient motion delta (512 values)
        delta_flat = delta_i.ravel()

        # 3. Local motion flows (496 + 480 = 976 values)
        emdx_flat = emd_x.ravel()
        emdy_flat = emd_y.ravel()

        # 4. Higher-level LPTC tangentials (4 values: HS_L, HS_R, VS_Forward, Yaw)
        lptc_vec = np.array([hs_l, hs_r, vs_f, hs_l - hs_r], dtype=np.float32)

        # Concatenate into full stimulation vector
        # Total size: 512 + 512 + 496 + 480 + 4 = 2004 input channels
        currents = np.concatenate([lum_flat, delta_flat, emdx_flat, emdy_flat, lptc_vec])
        return currents.astype(np.float32)

    def _rate_encode_spikes(self, currents: np.ndarray, dt_s: float) -> np.ndarray:
        """Convert input currents to Poisson/Bernoulli spikes for the SNN input layer.

        Spike probability: P = 1 - exp(-rate * dt) approx clamp(current * gain, 0, 1)
        """
        # Rectify currents (positive excitation creates spikes)
        pos_currents = np.maximum(currents, 0.0)
        # Scale to firing rate [Hz], clamp max rate to 200 Hz
        rate_hz = np.clip(pos_currents * 50.0, 0.0, 200.0)
        prob = 1.0 - np.exp(-rate_hz * dt_s)
        # Random draw for stochastic Poisson spike generation
        spikes = (np.random.rand(*currents.shape) < prob).astype(np.uint8)
        return spikes


class RetinaVisualizer:
    """Renders a comprehensive real-time dashboard of Drosophila vision and neural responses."""

    def __init__(self, history_len: int = 60) -> None:
        self.history_len = history_len
        self.hs_left_history: Deque[float] = deque(maxlen=history_len)
        self.hs_right_history: Deque[float] = deque(maxlen=history_len)
        self.vs_forward_history: Deque[float] = deque(maxlen=history_len)
        self.yaw_history: Deque[float] = deque(maxlen=history_len)
        self.spike_raster_history: Deque[np.ndarray] = deque(maxlen=history_len)

    def render_dashboard(
        self,
        frame_bgr: np.ndarray,
        out: RetinaOutput,
        telemetry: Optional[Dict] = None,
    ) -> np.ndarray:
        """Render a 1280x720 composite dashboard showing biological vision stages."""
        # Update histories
        self.hs_left_history.append(out.lptc_hs_left)
        self.hs_right_history.append(out.lptc_hs_right)
        self.vs_forward_history.append(out.lptc_vs_forward)
        self.yaw_history.append(out.lptc_yaw_signal)
        # Sample first 64 channels for spike raster
        self.spike_raster_history.append(out.spikes[:64])

        # Canvas: 1280 x 760 dark themed
        canvas_h, canvas_w = 760, 1280
        canvas = np.zeros((canvas_h, canvas_w, 3), dtype=np.uint8)
        canvas[:] = (20, 22, 28)  # Deep grey/blue background

        # Header Title
        cv2.putText(
            canvas,
            "DROSOPHILA RETINA & MOTION SENSORY SYSTEM (FlyWire Codex Connectome)",
            (25, 30),
            cv2.FONT_HERSHEY_DUPLEX,
            0.62,
            (230, 230, 240),
            1,
        )
        fps_info = f"Retina: {out.processing_time_ms:.2f} ms | Budget: < 40 ms"
        cv2.putText(canvas, fps_info, (920, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.48, (100, 220, 100), 1)

        # -----------------------------------------------------------------
        # Panel 1: Original Screen Capture (Top Left: 440 x 300)
        # -----------------------------------------------------------------
        p1_x, p1_y, p1_w, p1_h = 25, 55, 420, 280
        orig_resized = cv2.resize(frame_bgr, (p1_w, p1_h))
        # Draw Left/Right Eye split line and FOE indicator
        cv2.line(orig_resized, (p1_w // 2, 0), (p1_w // 2, p1_h), (0, 200, 255), 1)
        cv2.circle(orig_resized, (p1_w // 2, int(p1_h * 0.45)), 5, (0, 0, 255), -1)
        canvas[p1_y : p1_y + p1_h, p1_x : p1_x + p1_w] = orig_resized
        self._draw_panel_border(canvas, p1_x, p1_y, p1_w, p1_h, "1. Raw Screen View (Split Hemifields)")

        # -----------------------------------------------------------------
        # Panel 2: Ommatidia Binocular Grid (Top Middle: 380 x 280)
        # -----------------------------------------------------------------
        p2_x, p2_y, p2_w, p2_h = 470, 55, 380, 280
        ommatidia_vis = self._render_ommatidia_mosaic(out.ommatidia_luminance, p2_w, p2_h)
        canvas[p2_y : p2_y + p2_h, p2_x : p2_x + p2_w] = ommatidia_vis
        self._draw_panel_border(canvas, p2_x, p2_y, p2_w, p2_h, "2. Ommatidia Array (2 x 16x16 Facets)")

        # -----------------------------------------------------------------
        # Panel 3: ON/OFF Lamina Channels (Top Right: 380 x 280)
        # -----------------------------------------------------------------
        p3_x, p3_y, p3_w, p3_h = 875, 55, 380, 280
        on_off_vis = self._render_on_off_map(out.on_channel, out.off_channel, p3_w, p3_h)
        canvas[p3_y : p3_y + p3_h, p3_x : p3_x + p3_w] = on_off_vis
        self._draw_panel_border(canvas, p3_x, p3_y, p3_w, p3_h, "3. Lamina ON/OFF Pathways (T4/T5)")

        # -----------------------------------------------------------------
        # Panel 4: Hassenstein-Reichardt Flow Vectors (Bottom Left: 420 x 360)
        # -----------------------------------------------------------------
        p4_x, p4_y, p4_w, p4_h = 25, 360, 420, 360
        flow_vis = self._render_flow_vectors(out.emd_x, out.emd_y, p4_w, p4_h)
        canvas[p4_y : p4_y + p4_h, p4_x : p4_x + p4_w] = flow_vis
        self._draw_panel_border(canvas, p4_x, p4_y, p4_w, p4_h, "4. 2D Hassenstein-Reichardt Motion Fields")

        # -----------------------------------------------------------------
        # Panel 5: LPTC Gauges & Activity Strip (Bottom Middle: 380 x 360)
        # -----------------------------------------------------------------
        p5_x, p5_y, p5_w, p5_h = 470, 360, 380, 360
        lptc_vis = self._render_lptc_panel(out, p5_w, p5_h)
        canvas[p5_y : p5_y + p5_h, p5_x : p5_x + p5_w] = lptc_vis
        self._draw_panel_border(canvas, p5_x, p5_y, p5_w, p5_h, "5. Lobula Plate Tangential Cells (LPTC)")

        # -----------------------------------------------------------------
        # Panel 6: SNN Input Spike Raster Plot (Bottom Right: 380 x 360)
        # -----------------------------------------------------------------
        p6_x, p6_y, p6_w, p6_h = 875, 360, 380, 360
        raster_vis = self._render_spike_raster(p6_w, p6_h)
        canvas[p6_y : p6_y + p6_h, p6_x : p6_x + p6_w] = raster_vis
        self._draw_panel_border(canvas, p6_x, p6_y, p6_w, p6_h, "6. SNN Input Spikes (Poisson Rate Coded)")

        return canvas

    def _draw_panel_border(
        self,
        canvas: np.ndarray,
        x: int,
        y: int,
        w: int,
        h: int,
        title: str,
    ) -> None:
        """Draw aesthetic border and title header for a panel."""
        cv2.rectangle(canvas, (x - 2, y - 2), (x + w + 2, y + h + 2), (60, 68, 85), 1)
        # Title background strip
        cv2.rectangle(canvas, (x, y), (x + w, y + 22), (35, 40, 52), -1)
        cv2.putText(
            canvas,
            title,
            (x + 8, y + 16),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.45,
            (180, 210, 255),
            1,
        )

    def _render_ommatidia_mosaic(self, lum: np.ndarray, w: int, h: int) -> np.ndarray:
        """Render discrete circular ommatidia facets in fly-eye style."""
        vis = np.zeros((h, w, 3), dtype=np.uint8)
        grid_h, grid_w = lum.shape
        cell_w = (w - 20) / grid_w
        cell_h = (h - 55) / grid_h
        radius = int(min(cell_w, cell_h) * 0.42)

        for r in range(grid_h):
            for c in range(grid_w):
                cx = int(10 + c * cell_w + cell_w / 2)
                cy = int(28 + r * cell_h + cell_h / 2)
                val = int(np.clip(lum[r, c] * 255.0, 0, 255))
                # Fly-eye pseudocolor: amber / green-gold tint
                color = (int(val * 0.4), int(val * 0.85), int(val))
                cv2.circle(vis, (cx, cy), radius, color, -1)
                cv2.circle(vis, (cx, cy), radius, (40, 40, 40), 1)

        # Draw divider between Left Eye and Right Eye
        mid_x = int(10 + (grid_w // 2) * cell_w)
        cv2.line(vis, (mid_x, 26), (mid_x, h - 25), (0, 160, 255), 2)
        cv2.putText(vis, "LEFT EYE (16x16)", (20, h - 8), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 200, 255), 1)
        cv2.putText(vis, "RIGHT EYE (16x16)", (w - 145, h - 8), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 200, 255), 1)
        return vis

    def _render_on_off_map(self, on_ch: np.ndarray, off_ch: np.ndarray, w: int, h: int) -> np.ndarray:
        """Render ON (Green) and OFF (Red/Magenta) channel activations."""
        vis = np.zeros((h, w, 3), dtype=np.uint8)
        grid_h, grid_w = on_ch.shape
        cell_w = (w - 20) / grid_w
        cell_h = (h - 55) / grid_h

        # Normalize activations for visualization
        on_norm = np.clip(on_ch * 8.0, 0.0, 1.0)
        off_norm = np.clip(off_ch * 8.0, 0.0, 1.0)

        for r in range(grid_h):
            for c in range(grid_w):
                x1 = int(10 + c * cell_w)
                y1 = int(28 + r * cell_h)
                x2 = int(x1 + cell_w - 1)
                y2 = int(y1 + cell_h - 1)

                g_val = int(on_norm[r, c] * 255)
                r_val = int(off_norm[r, c] * 255)
                color = (int(r_val * 0.3), g_val, r_val)  # Green for ON, Red for OFF
                cv2.rectangle(vis, (x1, y1), (x2, y2), color, -1)

        # Legend
        cv2.putText(vis, "ON Pathway (Brightness Increase)", (20, h - 22), cv2.FONT_HERSHEY_SIMPLEX, 0.38, (0, 255, 0), 1)
        cv2.putText(vis, "OFF Pathway (Darkness Edges)", (20, h - 8), cv2.FONT_HERSHEY_SIMPLEX, 0.38, (0, 80, 255), 1)
        return vis

    def _render_flow_vectors(self, emd_x: np.ndarray, emd_y: np.ndarray, w: int, h: int) -> np.ndarray:
        """Render 2D motion velocity vector quiver field."""
        vis = np.zeros((h, w, 3), dtype=np.uint8)
        gh, gw = emd_y.shape[0], emd_x.shape[1]
        step_x = (w - 30) / gw
        step_y = (h - 55) / gh

        # Draw grid points and vectors
        for r in range(0, gh, 1):
            for c in range(0, gw, 1):
                cx = int(15 + c * step_x + step_x / 2)
                cy = int(32 + r * step_y + step_y / 2)

                vx = emd_x[min(r, emd_x.shape[0] - 1), c] * 12.0
                vy = emd_y[r, min(c, emd_y.shape[1] - 1)] * 12.0
                mag = np.sqrt(vx**2 + vy**2)

                # Small origin dot
                cv2.circle(vis, (cx, cy), 1, (100, 100, 110), -1)

                if mag > 1.0:
                    ex = int(np.clip(cx + vx, 5, w - 5))
                    ey = int(np.clip(cy + vy, 28, h - 5))
                    # Color mapped by speed magnitude
                    color = (255, 200, 0) if mag < 8.0 else (0, 120, 255)
                    cv2.arrowedLine(vis, (cx, cy), (ex, ey), color, 1, tipLength=0.35)

        cv2.putText(vis, "Optic Flow: Yellow = Moderate, Red/Orange = Fast", (15, h - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.38, (180, 180, 190), 1)
        return vis

    def _render_lptc_panel(self, out: RetinaOutput, w: int, h: int) -> np.ndarray:
        """Render animated gauge meters for HS (Yaw) and VS (Forward Expansion)."""
        vis = np.zeros((h, w, 3), dtype=np.uint8)

        # Bar Gauge Helper
        def draw_gauge(y_pos: int, label: str, value: float, v_min: float, v_max: float, color: Tuple[int, int, int]) -> None:
            cv2.putText(vis, label, (15, y_pos), cv2.FONT_HERSHEY_SIMPLEX, 0.40, (220, 220, 230), 1)
            gauge_w = w - 195
            gx = 145
            gy = y_pos - 12
            # Background bar
            cv2.rectangle(vis, (gx, gy), (gx + gauge_w, gy + 14), (45, 50, 62), -1)
            # Center zero tick
            mid_bar = gx + gauge_w // 2
            cv2.line(vis, (mid_bar, gy - 2), (mid_bar, gy + 16), (120, 120, 130), 1)

            # Fill bar
            norm_val = np.clip((value - v_min) / (v_max - v_min), 0.0, 1.0)
            fill_x = int(gx + norm_val * gauge_w)
            if fill_x > mid_bar:
                cv2.rectangle(vis, (mid_bar, gy + 2), (fill_x, gy + 12), color, -1)
            else:
                cv2.rectangle(vis, (fill_x, gy + 2), (mid_bar, gy + 12), color, -1)

            val_str = f"{value:+.2f}"
            cv2.putText(vis, val_str, (gx + gauge_w + 6, y_pos), cv2.FONT_HERSHEY_SIMPLEX, 0.36, color, 1)

        draw_gauge(50, "HS-Left (Yaw R)", out.lptc_hs_left, -1.5, 1.5, (0, 220, 255))
        draw_gauge(85, "HS-Right (Yaw L)", out.lptc_hs_right, -1.5, 1.5, (0, 220, 255))
        draw_gauge(120, "Net Yaw Rotation", out.lptc_yaw_signal, -2.5, 2.5, (255, 140, 0))
        draw_gauge(155, "VS-Forward Speed", out.lptc_vs_forward, -1.0, 3.0, (100, 255, 100))

        # Mini Sparkline History (Bottom half of panel)
        chart_y = 195
        chart_h = h - chart_y - 25
        chart_w = w - 30
        cv2.rectangle(vis, (15, chart_y), (15 + chart_w, chart_y + chart_h), (30, 34, 44), -1)
        cv2.putText(vis, "LPTC Motion Signal History (Past 60 Frames)", (20, chart_y - 8), cv2.FONT_HERSHEY_SIMPLEX, 0.38, (160, 170, 185), 1)

        if len(self.yaw_history) > 1:
            points_yaw = []
            points_vs = []
            n = len(self.yaw_history)
            for i in range(n):
                px = int(15 + (i / max(1, self.history_len - 1)) * chart_w)
                py_yaw = int(chart_y + chart_h / 2 - (self.yaw_history[i] / 2.0) * (chart_h / 2.2))
                py_yaw = np.clip(py_yaw, chart_y, chart_y + chart_h)
                points_yaw.append((px, py_yaw))

                py_vs = int(chart_y + chart_h - 10 - (self.vs_forward_history[i] / 2.5) * (chart_h - 20))
                py_vs = np.clip(py_vs, chart_y, chart_y + chart_h)
                points_vs.append((px, py_vs))

            for i in range(len(points_yaw) - 1):
                cv2.line(vis, points_yaw[i], points_yaw[i + 1], (255, 140, 0), 2)
                cv2.line(vis, points_vs[i], points_vs[i + 1], (100, 255, 100), 2)

        cv2.putText(vis, "Orange: Yaw (Turn) | Green: VS (Speed)", (20, h - 8), cv2.FONT_HERSHEY_SIMPLEX, 0.36, (180, 180, 190), 1)
        return vis

    def _render_spike_raster(self, w: int, h: int) -> np.ndarray:
        """Render a biological spike raster plot (Neurons x Time)."""
        vis = np.zeros((h, w, 3), dtype=np.uint8)
        num_channels = 64
        raster_x = 35
        raster_y = 48
        raster_w = w - 50
        raster_h = h - 75

        cv2.rectangle(vis, (raster_x, raster_y), (raster_x + raster_w, raster_y + raster_h), (25, 28, 36), -1)

        # Plot spikes
        if self.spike_raster_history:
            history_list = list(self.spike_raster_history)
            for t_idx, spike_arr in enumerate(history_list):
                tx = int(raster_x + (t_idx / max(1, self.history_len - 1)) * raster_w)
                active_indices = np.where(spike_arr > 0)[0]
                for ch_idx in active_indices:
                    ty = int(raster_y + (ch_idx / num_channels) * raster_h)
                    cv2.line(vis, (tx, ty), (tx, ty + 2), (0, 255, 220), 1)

        # Labels
        cv2.putText(vis, "Input Neurons (ID 0..64)", (raster_x, 38), cv2.FONT_HERSHEY_SIMPLEX, 0.38, (160, 170, 185), 1)
        cv2.putText(vis, "Time Step -> (Recent frames)", (raster_x + 10, h - 8), cv2.FONT_HERSHEY_SIMPLEX, 0.38, (160, 170, 185), 1)
        return vis


def run_live_retina_stream(use_synthetic: bool = True) -> None:
    """Run an interactive real-time visual stream of the retina dashboard."""
    from game_harness import PolytrackHarness, ScreenCapture

    print("\n" + "=" * 60)
    print("STARTING DROSOPHILA RETINA DASHBOARD STREAM")
    print(f"Mode: {'SYNTHETIC POLYTRACK SIMULATION' if use_synthetic else 'LIVE SCREEN CAPTURE'}")
    print("Press 'q' or ESC in preview window to exit.")
    print("Press 's' to save a dashboard screenshot to disk.")
    print("=" * 60 + "\n")

    harness = PolytrackHarness(fallback_synthetic=use_synthetic)
    retina = DrosophilaRetina()
    visualizer = RetinaVisualizer()

    win_name = "Drosophila Visual Cortex Simulator (Module 2)"
    cv2.namedWindow(win_name, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(win_name, 1280, 760)

    frame_count = 0
    t_start = time.perf_counter()

    try:
        while True:
            # Step 1: Capture game frame
            if use_synthetic:
                # Add gentle camera yaw swing to demonstrate optical flow
                frame_count += 1
                phase = frame_count * 0.05
                is_falling = (frame_count // 300) % 2 == 1  # Periodic test fall
                frame_bgr = ScreenCapture.generate_synthetic_polytrack_frame(800, 600, is_falling=is_falling)
                # Simulate steering displacement
                shift = int(np.sin(phase) * 30.0)
                M = np.float32([[1, 0, shift], [0, 1, 0]])
                frame_bgr = cv2.warpAffine(frame_bgr, M, (800, 600), borderMode=cv2.BORDER_REFLECT)
                telemetry = {"is_falling": is_falling, "synthetic": True}
            else:
                frame_bgr, _ = harness.capture.grab_bgr()
                _, is_falling, telemetry = harness.step()

            # Step 2: Drosophila visual processing
            retina_out = retina.process(frame_bgr)

            # Step 3: Render composite dashboard
            dashboard = visualizer.render_dashboard(frame_bgr, retina_out, telemetry)

            cv2.imshow(win_name, dashboard)
            key = cv2.waitKey(1) & 0xFF
            if key in [ord("q"), 27]:  # 'q' or ESC
                break
            elif key == ord("s"):
                snap_path = config.BASE_DIR / f"retina_snapshot_{int(time.time())}.png"
                cv2.imwrite(str(snap_path), dashboard)
                print(f"[SAVED] Retina dashboard snapshot saved to: {snap_path}")
            elif key == ord("r"):
                retina.reset()
                print("[RESET] Retina temporal filters reset.")

    finally:
        harness.inputs.release_all()
        cv2.destroyAllWindows()
        fps = frame_count / max(0.001, (time.perf_counter() - t_start))
        print(f"\nRetina stream closed. Average frame rate: {fps:.1f} FPS.")


def main() -> None:
    """CLI entrypoint for testing and visualizing the Drosophila retina."""
    parser = argparse.ArgumentParser(description="Drosophila Retina & Motion Correlator (Module 2)")
    parser.add_argument("--stream", action="store_true", help="Launch live retina visual dashboard")
    parser.add_argument("--live-screen", action="store_true", help="Capture live desktop instead of synthetic")
    parser.add_argument("--benchmark", action="store_true", help="Benchmark retina computation throughput")
    parser.add_argument("--save-snapshot", action="store_true", help="Save a single snapshot image of dashboard")
    parser.add_argument("--cycles", type=int, default=300, help="Benchmark cycles")

    args = parser.parse_args()

    if args.benchmark or (not args.stream and not args.save_snapshot):
        # Run computational benchmark by default
        print("\n" + "=" * 60)
        print(f"BENCHMARKING DROSOPHILA RETINA PIPELINE ({args.cycles} CYCLES)")
        print(f"Grid: {config.RETINA_GRID_HEIGHT} x {config.RETINA_GRID_WIDTH} (Binocular Ommatidia)")
        print("=" * 60)

        from game_harness import ScreenCapture
        retina = DrosophilaRetina()
        sample_frame = ScreenCapture.generate_synthetic_polytrack_frame(800, 600)

        # Warmup
        for _ in range(10):
            retina.process(sample_frame)

        times_ms = []
        for i in range(args.cycles):
            # Alternate horizontal translation to stimulate HRC
            shift = int(np.sin(i * 0.1) * 20.0)
            M = np.float32([[1, 0, shift], [0, 1, 0]])
            frame = cv2.warpAffine(sample_frame, M, (800, 600), borderMode=cv2.BORDER_REFLECT)

            out = retina.process(frame)
            times_ms.append(out.processing_time_ms)

        arr = np.array(times_ms)
        print("\n" + "=" * 60)
        print("RETINA PERFORMANCE REPORT")
        print("=" * 60)
        print(f" Samples Evaluated:      {len(arr)}")
        print(f" Mean Time:              {np.mean(arr):.3f} ms")
        print(f" Median Time:            {np.median(arr):.3f} ms")
        print(f" 95th Percentile (P95):  {np.percentile(arr, 95):.3f} ms")
        print(f" 99th Percentile (P99):  {np.percentile(arr, 99):.3f} ms")
        print(f" Min / Max Time:         {np.min(arr):.3f} ms / {np.max(arr):.3f} ms")
        print(f" Max Retina Throughput:  {1000.0 / np.mean(arr):.1f} FPS")
        print(f" Stimulation Vector Dim: {len(out.stimulation_currents)} channels")
        print(f" Spikes Active / Cycle:  {np.sum(out.spikes)} spikes")
        print("-" * 60)
        print(f" [PASS] Retina processing time ({np.mean(arr):.3f} ms) is negligible (< 1 ms),")
        print(" leaving > 38 ms of latency budget for SNN inference!")
        print("=" * 60 + "\n")

    if args.save_snapshot:
        from game_harness import ScreenCapture
        retina = DrosophilaRetina()
        visualizer = RetinaVisualizer()
        frame = ScreenCapture.generate_synthetic_polytrack_frame(800, 600)
        # Run a few steps so temporal filters fill up
        for i in range(10):
            M = np.float32([[1, 0, i * 3], [0, 1, 0]])
            f = cv2.warpAffine(frame, M, (800, 600), borderMode=cv2.BORDER_REFLECT)
            out = retina.process(f)
        dashboard = visualizer.render_dashboard(f, out)
        out_path = config.BASE_DIR / "retina_demo_dashboard.png"
        cv2.imwrite(str(out_path), dashboard)
        print(f"[OK] Saved retina dashboard demo to: {out_path}")

    if args.stream:
        run_live_retina_stream(use_synthetic=not args.live_screen)


if __name__ == "__main__":
    main()
